name: Setup Node.js using .nvmrc

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
        cache-dependency-path: "package-lock.json"
