services:
  frontend:
    build:
      target: dev-ci # this stage in the Dockerfile copies files because we are not using the mount

    # In CI we do NOT mount the repo into /app, because that can change ownership/permissions
    # and cause Next to fail writing next-env.d.ts or .next.
    volumes: !reset
      - type: volume # anonymous volume
        target: /app/node_modules
      - type: volume # named volume
        source: nextjs_cache
        target: /app/apps/web/.next
      # Explicitly ignore node_modules and .next folders in the volume mount to prevent conflicts between host and container dependencies/build cache for both root folder and app folder
