services:
  frontend:
    # In CI we do NOT mount the repo into /app, because that can change ownership/permissions
    # and cause Next to fail writing next-env.d.ts or .next.
    build: 
      context: . 
      dockerfile: ci.Dockerfile
      cache_from:  
        - type=local,src=cache-docker-frontend 
      cache_to:  
        - type=local,dest=cache-docker-frontend
    volumes: !reset
  db:
    build: 
      cache_from:  
        - type=local,src=cache-docker-db 
      cache_to:  
        - type=local,dest=cache-docker-db 
  backend:
    build: 
      cache_from:  
        - type=local,src=cache-docker-backend
      cache_to:  
        - type=local,dest=cache-docker-backend
