"""add earthquake_risk table

Revision ID: 622d3c31bda0
Revises: 6b7656592b34
Create Date: 2026-09-16 04:40:52.763885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "622d3c31bda0"
down_revision: Union[str, None] = "6b7656592b34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "earthquake_risk",
        sa.Column("tract_fips", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("risk_rating", sa.String(), nullable=True),
        sa.Column(
            "update_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("tract_fips"),
    )
    op.create_geospatial_index(
        "idx_earthquake_risk_geometry",
        "earthquake_risk",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_earthquake_risk_geometry",
        table_name="earthquake_risk",
        postgresql_using="gist",
        column_name="geometry",
    )
    op.drop_geospatial_table("earthquake_risk")
    # ### end Alembic commands ###
