// This file is generated by scripts/convert-dtcg-tokens-to-chakra.mjs.
// Do not edit it directly; update theme-merged/theme.tokens.json instead.

import { defineSemanticTokens, defineTokens } from "@chakra-ui/react";

export const tokens = defineTokens({
  colors: {
    black: {
      value: "#09090b",
    },
    white: {
      DEFAULT: {
        value: "#ffffff",
      },
    },
    whiteAlpha: {
      "50": {
        value: "rgb(255 255 255 / 0.04)",
      },
      "100": {
        value: "rgb(255 255 255 / 0.06)",
      },
      "200": {
        value: "rgb(255 255 255 / 0.08)",
      },
      "300": {
        value: "rgb(255 255 255 / 0.16)",
      },
      "400": {
        value: "rgb(255 255 255 / 0.24)",
      },
      "500": {
        value: "rgb(255 255 255 / 0.36)",
      },
      "600": {
        value: "rgb(255 255 255 / 0.48)",
      },
      "700": {
        value: "rgb(255 255 255 / 0.64)",
      },
      "800": {
        value: "#ffffffcc",
      },
      "900": {
        value: "rgb(255 255 255 / 0.92)",
      },
      "950": {
        value: "rgb(255 255 255 / 0.95)",
      },
    },
    blackAlpha: {
      "50": {
        value: "rgb(0 0 0 / 0.04)",
      },
      "100": {
        value: "rgb(0 0 0 / 0.06)",
      },
      "200": {
        value: "rgb(0 0 0 / 0.08)",
      },
      "300": {
        value: "rgb(0 0 0 / 0.16)",
      },
      "400": {
        value: "rgb(0 0 0 / 0.24)",
      },
      "500": {
        value: "rgb(0 0 0 / 0.36)",
      },
      "600": {
        value: "rgb(0 0 0 / 0.48)",
      },
      "700": {
        value: "rgb(0 0 0 / 0.64)",
      },
      "800": {
        value: "#000000cc",
      },
      "900": {
        value: "rgb(0 0 0 / 0.92)",
      },
      "950": {
        value: "rgb(0 0 0 / 0.95)",
      },
    },
    gray: {
      "50": {
        value: "#fafafa",
      },
      "100": {
        value: "#f4f4f5",
      },
      "200": {
        value: "#e4e4e7",
      },
      "300": {
        value: "#d4d4d8",
      },
      "400": {
        value: "#a1a1aa",
      },
      "500": {
        value: "#71717a",
      },
      "600": {
        value: "#52525b",
      },
      "700": {
        value: "#3f3f46",
      },
      "800": {
        value: "#27272a",
      },
      "900": {
        value: "#18181b",
      },
      "950": {
        value: "#111111",
      },
    },
    red: {
      "50": {
        value: "#fef2f2",
      },
      "100": {
        value: "#fee2e2",
      },
      "200": {
        value: "#fecaca",
      },
      "300": {
        value: "#fca5a5",
      },
      "400": {
        value: "#f87171",
      },
      "500": {
        value: "#ef4444",
      },
      "600": {
        value: "#dc2626",
      },
      "700": {
        value: "#991919",
      },
      "800": {
        value: "#511111",
      },
      "900": {
        value: "#300c0c",
      },
      "950": {
        value: "#1f0808",
      },
      DEFAULT: {
        value: "#c53030",
      },
    },
    orange: {
      "50": {
        value: "#fff7ed",
      },
      "100": {
        value: "#ffedd5",
      },
      "200": {
        value: "#fed7aa",
      },
      "300": {
        value: "#fdba74",
      },
      "400": {
        value: "#fb923c",
      },
      "500": {
        value: "#f97316",
      },
      "600": {
        value: "#ea580c",
      },
      "700": {
        value: "#92310a",
      },
      "800": {
        value: "#6c2710",
      },
      "900": {
        value: "#3b1106",
      },
      "950": {
        value: "#220a04",
      },
      DEFAULT: {
        value: "#f6ad55",
      },
    },
    yellow: {
      "50": {
        value: "#fefce8",
      },
      "100": {
        value: "#fef9c3",
      },
      "200": {
        value: "#fef08a",
      },
      "300": {
        value: "#fde047",
      },
      "400": {
        value: "#facc15",
      },
      "500": {
        value: "#eab308",
      },
      "600": {
        value: "#ca8a04",
      },
      "700": {
        value: "#845209",
      },
      "800": {
        value: "#713f12",
      },
      "900": {
        value: "#422006",
      },
      "950": {
        value: "#281304",
      },
      DEFAULT: {
        value: "#ecc94b",
      },
    },
    green: {
      "50": {
        value: "#f0fdf4",
      },
      "100": {
        value: "#dcfce7",
      },
      "200": {
        value: "#bbf7d0",
      },
      "300": {
        value: "#86efac",
      },
      "400": {
        value: "#4ade80",
      },
      "500": {
        value: "#22c55e",
      },
      "600": {
        value: "#16a34a",
      },
      "700": {
        value: "#116932",
      },
      "800": {
        value: "#124a28",
      },
      "900": {
        value: "#042713",
      },
      "950": {
        value: "#03190c",
      },
      DEFAULT: {
        value: "#25855a",
      },
    },
    teal: {
      "50": {
        value: "#f0fdfa",
      },
      "100": {
        value: "#ccfbf1",
      },
      "200": {
        value: "#99f6e4",
      },
      "300": {
        value: "#5eead4",
      },
      "400": {
        value: "#2dd4bf",
      },
      "500": {
        value: "#14b8a6",
      },
      "600": {
        value: "#0d9488",
      },
      "700": {
        value: "#0c5d56",
      },
      "800": {
        value: "#114240",
      },
      "900": {
        value: "#032726",
      },
      "950": {
        value: "#021716",
      },
    },
    blue: {
      "50": {
        value: "#eff6ff",
      },
      "100": {
        value: "#dbeafe",
      },
      "200": {
        value: "#bfdbfe",
      },
      "300": {
        value: "#a3cfff",
      },
      "400": {
        value: "#60a5fa",
      },
      "500": {
        value: "#3b82f6",
      },
      "600": {
        value: "#0088ff",
      },
      "700": {
        value: "#173da6",
      },
      "800": {
        value: "#1a3478",
      },
      "900": {
        value: "#14204a",
      },
      "950": {
        value: "#0c142e",
      },
      text: {
        value: "#2b6cb0",
      },
    },
    cyan: {
      "50": {
        value: "#ecfeff",
      },
      "100": {
        value: "#cffafe",
      },
      "200": {
        value: "#a5f3fc",
      },
      "300": {
        value: "#67e8f9",
      },
      "400": {
        value: "#22d3ee",
      },
      "500": {
        value: "#06b6d4",
      },
      "600": {
        value: "#0891b2",
      },
      "700": {
        value: "#0c5c72",
      },
      "800": {
        value: "#134152",
      },
      "900": {
        value: "#072a38",
      },
      "950": {
        value: "#051b24",
      },
    },
    purple: {
      "50": {
        value: "#faf5ff",
      },
      "100": {
        value: "#f3e8ff",
      },
      "200": {
        value: "#e9d5ff",
      },
      "300": {
        value: "#d8b4fe",
      },
      "400": {
        value: "#c084fc",
      },
      "500": {
        value: "#a855f7",
      },
      "600": {
        value: "#9333ea",
      },
      "700": {
        value: "#641ba3",
      },
      "800": {
        value: "#4a1772",
      },
      "900": {
        value: "#2f0553",
      },
      "950": {
        value: "#1a032e",
      },
    },
    pink: {
      "50": {
        value: "#fdf2f8",
      },
      "100": {
        value: "#fce7f3",
      },
      "200": {
        value: "#fbcfe8",
      },
      "300": {
        value: "#f9a8d4",
      },
      "400": {
        value: "#f472b6",
      },
      "500": {
        value: "#ec4899",
      },
      "600": {
        value: "#db2777",
      },
      "700": {
        value: "#a41752",
      },
      "800": {
        value: "#6d0e34",
      },
      "900": {
        value: "#45061f",
      },
      "950": {
        value: "#2c0514",
      },
      DEFAULT: {
        value: "#ed64a6",
      },
    },
    grey: {
      "200": {
        value: "#e2e8f0",
      },
      "400": {
        value: "#a0aec0",
      },
      "600": {
        value: "#4a5568",
      },
      "900": {
        value: "#171923",
      },
    },
    peach: {
      DEFAULT: {
        value: "#f5f5f5",
      },
    },
    transparent: {
      value: "transparent",
    },
    current: {
      value: "currentColor",
    },
  },
  spacing: {
    "0": {
      value: "0px",
    },
    "1": {
      value: "0.25rem",
    },
    "2": {
      value: "0.5rem",
    },
    "3": {
      value: "0.75rem",
    },
    "4": {
      value: "1rem",
    },
    "5": {
      value: "1.25rem",
    },
    "6": {
      value: "1.5rem",
    },
    "7": {
      value: "1.75rem",
    },
    "8": {
      value: "2rem",
    },
    "9": {
      value: "2.25rem",
    },
    "10": {
      value: "2.5rem",
    },
    "11": {
      value: "2.75rem",
    },
    "12": {
      value: "3rem",
    },
    "14": {
      value: "3.5rem",
    },
    "16": {
      value: "4rem",
    },
    "20": {
      value: "5rem",
    },
    "24": {
      value: "6rem",
    },
    "28": {
      value: "7rem",
    },
    "32": {
      value: "8rem",
    },
    "36": {
      value: "9rem",
    },
    "40": {
      value: "10rem",
    },
    "44": {
      value: "11rem",
    },
    "48": {
      value: "12rem",
    },
    "52": {
      value: "13rem",
    },
    "56": {
      value: "14rem",
    },
    "60": {
      value: "15rem",
    },
    "64": {
      value: "16rem",
    },
    "72": {
      value: "18rem",
    },
    "80": {
      value: "20rem",
    },
    "96": {
      value: "24rem",
    },
    "0.5": {
      value: "0.125rem",
    },
    "1.5": {
      value: "0.375rem",
    },
    "2.5": {
      value: "0.625rem",
    },
    "3.5": {
      value: "0.875rem",
    },
    "4.5": {
      value: "1.125rem",
    },
    auto: {
      value: "auto",
    },
    "1/2": {
      value: "50%",
    },
  },
  sizes: {
    "1": {
      value: "0.25rem",
    },
    "2": {
      value: "0.5rem",
    },
    "3": {
      value: "0.75rem",
    },
    "4": {
      value: "1rem",
    },
    "5": {
      value: "1.25rem",
    },
    "6": {
      value: "1.5rem",
    },
    "7": {
      value: "1.75rem",
    },
    "8": {
      value: "2rem",
    },
    "9": {
      value: "2.25rem",
    },
    "10": {
      value: "2.5rem",
    },
    "11": {
      value: "2.75rem",
    },
    "12": {
      value: "3rem",
    },
    "14": {
      value: "3.5rem",
    },
    "16": {
      value: "4rem",
    },
    "20": {
      value: "5rem",
    },
    "24": {
      value: "6rem",
    },
    "28": {
      value: "7rem",
    },
    "32": {
      value: "8rem",
    },
    "36": {
      value: "9rem",
    },
    "40": {
      value: "10rem",
    },
    "44": {
      value: "11rem",
    },
    "48": {
      value: "12rem",
    },
    "52": {
      value: "13rem",
    },
    "56": {
      value: "14rem",
    },
    "60": {
      value: "15rem",
    },
    "64": {
      value: "16rem",
    },
    "72": {
      value: "18rem",
    },
    "80": {
      value: "20rem",
    },
    "96": {
      value: "24rem",
    },
    "3xs": {
      value: "14rem",
    },
    "2xs": {
      value: "16rem",
    },
    xs: {
      value: "20rem",
    },
    sm: {
      value: "24rem",
    },
    md: {
      value: "28rem",
    },
    lg: {
      value: "32rem",
    },
    xl: {
      value: "36rem",
    },
    "2xl": {
      value: "42rem",
    },
    "3xl": {
      value: "48rem",
    },
    "4xl": {
      value: "56rem",
    },
    "5xl": {
      value: "64rem",
    },
    "6xl": {
      value: "72rem",
    },
    "7xl": {
      value: "80rem",
    },
    "8xl": {
      value: "90rem",
    },
    "0.5": {
      value: "0.125rem",
    },
    "1.5": {
      value: "0.375rem",
    },
    "2.5": {
      value: "0.625rem",
    },
    "3.5": {
      value: "0.875rem",
    },
    "4.5": {
      value: "1.125rem",
    },
    "1/2": {
      value: "50%",
    },
    "1/3": {
      value: "33.333333%",
    },
    "2/3": {
      value: "66.666667%",
    },
    "1/4": {
      value: "25%",
    },
    "3/4": {
      value: "75%",
    },
    "1/5": {
      value: "20%",
    },
    "2/5": {
      value: "40%",
    },
    "3/5": {
      value: "60%",
    },
    "4/5": {
      value: "80%",
    },
    "1/6": {
      value: "16.666667%",
    },
    "2/6": {
      value: "33.333333%",
    },
    "3/6": {
      value: "50%",
    },
    "4/6": {
      value: "66.666667%",
    },
    "5/6": {
      value: "83.333333%",
    },
    "1/12": {
      value: "8.333333%",
    },
    "2/12": {
      value: "16.666667%",
    },
    "3/12": {
      value: "25%",
    },
    "4/12": {
      value: "33.333333%",
    },
    "5/12": {
      value: "41.666667%",
    },
    "6/12": {
      value: "50%",
    },
    "7/12": {
      value: "58.333333%",
    },
    "8/12": {
      value: "66.666667%",
    },
    "9/12": {
      value: "75%",
    },
    "10/12": {
      value: "83.333333%",
    },
    "11/12": {
      value: "91.666667%",
    },
    max: {
      value: "max-content",
    },
    min: {
      value: "min-content",
    },
    fit: {
      value: "fit-content",
    },
    prose: {
      value: "60ch",
    },
    full: {
      value: "100%",
    },
    dvh: {
      value: "100dvh",
    },
    svh: {
      value: "100svh",
    },
    lvh: {
      value: "100lvh",
    },
    dvw: {
      value: "100dvw",
    },
    svw: {
      value: "100svw",
    },
    lvw: {
      value: "100lvw",
    },
    vw: {
      value: "100vw",
    },
    vh: {
      value: "100vh",
    },
    unset: {
      value: "unset",
    },
    auto: {
      value: "auto",
    },
    none: {
      value: "none",
    },
  },
  fonts: {
    heading: {
      value: "var(--font-manrope), sans-serif",
    },
    body: {
      value: "var(--font-inter), sans-serif",
    },
    mono: {
      value:
        "SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace",
    },
  },
  fontSizes: {
    "2xs": {
      value: "0.625rem",
    },
    xs: {
      value: "0.75rem",
    },
    sm: {
      value: "0.875rem",
    },
    md: {
      value: "1rem",
    },
    lg: {
      value: "1.125rem",
    },
    xl: {
      value: "1.25rem",
    },
    "2xl": {
      value: "1.5rem",
    },
    "3xl": {
      value: "1.875rem",
    },
    "4xl": {
      value: "2.25rem",
    },
    "5xl": {
      value: "3rem",
    },
    "6xl": {
      value: "3.75rem",
    },
    "7xl": {
      value: "4.5rem",
    },
    "8xl": {
      value: "6rem",
    },
    "9xl": {
      value: "8rem",
    },
  },
  fontWeights: {
    thin: {
      value: 100,
    },
    extralight: {
      value: 200,
    },
    light: {
      value: 300,
    },
    normal: {
      value: 400,
    },
    medium: {
      value: 500,
    },
    semibold: {
      value: 600,
    },
    bold: {
      value: 700,
    },
    extrabold: {
      value: 800,
    },
    black: {
      value: 900,
    },
  },
  lineHeights: {
    shorter: {
      value: 1.25,
    },
    short: {
      value: 1.375,
    },
    moderate: {
      value: 1.5,
    },
    tall: {
      value: 1.625,
    },
    taller: {
      value: 2,
    },
    shortest: {
      value: 1,
    },
  },
  radii: {
    "2xs": {
      value: "0.0625rem",
    },
    xs: {
      value: "0.125rem",
    },
    sm: {
      value: "0.25rem",
    },
    md: {
      value: "0.375rem",
    },
    lg: {
      value: "0.5rem",
    },
    xl: {
      value: "0.75rem",
    },
    "2xl": {
      value: "1rem",
    },
    "3xl": {
      value: "1.5rem",
    },
    "4xl": {
      value: "2rem",
    },
    full: {
      value: "9999px",
    },
    none: {
      value: "0",
    },
  },
  borderWidths: {
    "0.25": {
      value: "1px",
    },
  },
  borderStyles: {
    solid: {
      value: "solid",
    },
  },
  durations: {
    fastest: {
      value: "50ms",
    },
    faster: {
      value: "100ms",
    },
    fast: {
      value: "150ms",
    },
    moderate: {
      value: "200ms",
    },
    slow: {
      value: "300ms",
    },
    slower: {
      value: "400ms",
    },
    slowest: {
      value: "500ms",
    },
  },
  easings: {
    "ease-in": {
      value: "cubic-bezier(0.42, 0, 1, 1)",
    },
    "ease-out": {
      value: "cubic-bezier(0, 0, 0.58, 1)",
    },
    "ease-in-out": {
      value: "cubic-bezier(0.42, 0, 0.58, 1)",
    },
    "ease-in-smooth": {
      value: "cubic-bezier(0.32, 0.72, 0, 1)",
    },
  },
  blurs: {
    sm: {
      value: "4px",
    },
    md: {
      value: "8px",
    },
    lg: {
      value: "12px",
    },
    xl: {
      value: "16px",
    },
    "2xl": {
      value: "24px",
    },
    "3xl": {
      value: "40px",
    },
    "4xl": {
      value: "64px",
    },
    none: {
      value: " ",
    },
  },
  zIndex: {
    hide: {
      value: -1,
    },
    base: {
      value: 0,
    },
    docked: {
      value: 10,
    },
    dropdown: {
      value: 1000,
    },
    sticky: {
      value: 1100,
    },
    banner: {
      value: 1200,
    },
    overlay: {
      value: 1300,
    },
    modal: {
      value: 1400,
    },
    popover: {
      value: 1500,
    },
    skipNav: {
      value: 1600,
    },
    toast: {
      value: 1700,
    },
    tooltip: {
      value: 1800,
    },
    max: {
      value: 2147483647,
    },
  },
  letterSpacings: {
    tighter: {
      value: "-0.05em",
    },
    tight: {
      value: "-0.025em",
    },
    wide: {
      value: "0.025em",
    },
    wider: {
      value: "0.05em",
    },
    widest: {
      value: "0.1em",
    },
  },
  gradients: {
    blue: {
      value:
        "radial-gradient(120% 180% at 17.81% 82.6%, {colors.blueGradientFrom} 0%, {colors.blueGradientTo} 100%);",
    },
  },
  aspectRatios: {
    square: {
      value: "1 / 1",
    },
    landscape: {
      value: "4 / 3",
    },
    portrait: {
      value: "3 / 4",
    },
    wide: {
      value: "16 / 9",
    },
    ultrawide: {
      value: "18 / 5",
    },
    golden: {
      value: "1.618 / 1",
    },
  },
  animations: {
    spin: {
      value: "spin 1s linear infinite",
    },
    ping: {
      value: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
    },
    pulse: {
      value: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
    },
    bounce: {
      value: "bounce 1s infinite",
    },
  },
  borders: {
    xs: {
      value: "0.5px solid",
    },
    sm: {
      value: "1px solid",
    },
    md: {
      value: "2px solid",
    },
    lg: {
      value: "4px solid",
    },
    xl: {
      value: "8px solid",
    },
    none: {
      value: "none",
    },
    search: {
      value: "{borderWidths.0.25} {borderStyles.solid} {colors.grey.600}",
    },
  },
  cursor: {
    button: {
      value: "pointer",
    },
    checkbox: {
      value: "default",
    },
    disabled: {
      value: "not-allowed",
    },
    menuitem: {
      value: "default",
    },
    option: {
      value: "default",
    },
    radio: {
      value: "default",
    },
    slider: {
      value: "default",
    },
    switch: {
      value: "pointer",
    },
  },
});

export const semanticTokens = defineSemanticTokens({
  colors: {
    blueSwitch: {
      value: "#3182ce",
    },
    blueIcon: {
      value: "#4863a9",
    },
    blueIconBackground: {
      value: "#eff4fc",
    },
    blueBackground: {
      value: "#2c5282",
    },
    tsunamiBlue: {
      value: "#63b3ed",
    },
    lightGrey: {
      value: "#c8cace",
    },
    labelGrey: {
      value: "#bfb9b9",
    },
    warningRed: {
      value: "#b53d37",
    },
    blueGradientFrom: {
      value: "#3b6294",
    },
    blueGradientTo: {
      value: "#183252",
    },
    cooperativeGesturesOverlay: {
      value: "#00000080",
    },
    bg: {
      subtle: {
        value: {
          _light: "{colors.gray.50}",
          _dark: "{colors.gray.950}",
        },
      },
      muted: {
        value: {
          _light: "{colors.gray.100}",
          _dark: "{colors.gray.900}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.gray.200}",
          _dark: "{colors.gray.800}",
        },
      },
      inverted: {
        value: {
          _light: "{colors.black}",
          _dark: "{colors.white}",
        },
      },
      panel: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.gray.950}",
        },
      },
      error: {
        value: {
          _light: "{colors.red.50}",
          _dark: "{colors.red.950}",
        },
      },
      warning: {
        value: {
          _light: "{colors.orange.50}",
          _dark: "{colors.orange.950}",
        },
      },
      success: {
        value: {
          _light: "{colors.green.50}",
          _dark: "{colors.green.950}",
        },
      },
      info: {
        value: {
          _light: "{colors.blue.50}",
          _dark: "{colors.blue.950}",
        },
      },
    },
    fg: {
      muted: {
        value: {
          _light: "{colors.gray.600}",
          _dark: "{colors.gray.400}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.gray.400}",
          _dark: "{colors.gray.500}",
        },
      },
      inverted: {
        value: {
          _light: "{colors.gray.50}",
          _dark: "{colors.black}",
        },
      },
      error: {
        value: {
          _light: "{colors.red.500}",
          _dark: "{colors.red.400}",
        },
      },
      warning: {
        value: {
          _light: "{colors.orange.600}",
          _dark: "{colors.orange.300}",
        },
      },
      success: {
        value: {
          _light: "{colors.green.600}",
          _dark: "{colors.green.300}",
        },
      },
      info: {
        value: {
          _light: "{colors.blue.600}",
          _dark: "{colors.blue.300}",
        },
      },
    },
    border: {
      muted: {
        value: {
          _light: "{colors.gray.100}",
          _dark: "{colors.gray.900}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.gray.50}",
          _dark: "{colors.gray.950}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.gray.300}",
          _dark: "{colors.gray.700}",
        },
      },
      inverted: {
        value: {
          _light: "{colors.gray.800}",
          _dark: "{colors.gray.200}",
        },
      },
      error: {
        value: {
          _light: "{colors.red.500}",
          _dark: "{colors.red.400}",
        },
      },
      warning: {
        value: {
          _light: "{colors.orange.500}",
          _dark: "{colors.orange.400}",
        },
      },
      success: {
        value: {
          _light: "{colors.green.500}",
          _dark: "{colors.green.400}",
        },
      },
      info: {
        value: {
          _light: "{colors.blue.500}",
          _dark: "{colors.blue.400}",
        },
      },
    },
    gray: {
      contrast: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.black}",
        },
      },
      fg: {
        value: {
          _light: "{colors.gray.800}",
          _dark: "{colors.gray.200}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.gray.100}",
          _dark: "{colors.gray.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.gray.200}",
          _dark: "{colors.gray.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.gray.300}",
          _dark: "{colors.gray.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.gray.900}",
          _dark: "{colors.white}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.gray.400}",
          _dark: "{colors.gray.400}",
        },
      },
      border: {
        value: {
          _light: "{colors.gray.200}",
          _dark: "{colors.gray.800}",
        },
      },
    },
    red: {
      contrast: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.white}",
        },
      },
      fg: {
        value: {
          _light: "{colors.red.700}",
          _dark: "{colors.red.300}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.red.100}",
          _dark: "{colors.red.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.red.200}",
          _dark: "{colors.red.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.red.300}",
          _dark: "{colors.red.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.red.600}",
          _dark: "{colors.red.600}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.red.500}",
          _dark: "{colors.red.500}",
        },
      },
      border: {
        value: {
          _light: "{colors.red.500}",
          _dark: "{colors.red.400}",
        },
      },
    },
    orange: {
      contrast: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.black}",
        },
      },
      fg: {
        value: {
          _light: "{colors.orange.700}",
          _dark: "{colors.orange.300}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.orange.100}",
          _dark: "{colors.orange.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.orange.200}",
          _dark: "{colors.orange.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.orange.300}",
          _dark: "{colors.orange.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.orange.600}",
          _dark: "{colors.orange.500}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.orange.500}",
          _dark: "{colors.orange.500}",
        },
      },
      border: {
        value: {
          _light: "{colors.orange.500}",
          _dark: "{colors.orange.400}",
        },
      },
    },
    green: {
      contrast: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.white}",
        },
      },
      fg: {
        value: {
          _light: "{colors.green.700}",
          _dark: "{colors.green.300}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.green.100}",
          _dark: "{colors.green.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.green.200}",
          _dark: "{colors.green.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.green.300}",
          _dark: "{colors.green.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.green.600}",
          _dark: "{colors.green.600}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.green.500}",
          _dark: "{colors.green.500}",
        },
      },
      border: {
        value: {
          _light: "{colors.green.500}",
          _dark: "{colors.green.400}",
        },
      },
    },
    blue: {
      contrast: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.white}",
        },
      },
      fg: {
        value: {
          _light: "{colors.blue.700}",
          _dark: "{colors.blue.300}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.blue.100}",
          _dark: "{colors.blue.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.blue.200}",
          _dark: "{colors.blue.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.blue.300}",
          _dark: "{colors.blue.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.blue.600}",
          _dark: "{colors.blue.600}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.blue.500}",
          _dark: "{colors.blue.500}",
        },
      },
      border: {
        value: {
          _light: "{colors.blue.500}",
          _dark: "{colors.blue.400}",
        },
      },
    },
    yellow: {
      contrast: {
        value: {
          _light: "{colors.black}",
          _dark: "{colors.black}",
        },
      },
      fg: {
        value: {
          _light: "{colors.yellow.800}",
          _dark: "{colors.yellow.300}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.yellow.100}",
          _dark: "{colors.yellow.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.yellow.200}",
          _dark: "{colors.yellow.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.yellow.300}",
          _dark: "{colors.yellow.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.yellow.300}",
          _dark: "{colors.yellow.300}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.yellow.500}",
          _dark: "{colors.yellow.500}",
        },
      },
      border: {
        value: {
          _light: "{colors.yellow.500}",
          _dark: "{colors.yellow.500}",
        },
      },
    },
    teal: {
      contrast: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.white}",
        },
      },
      fg: {
        value: {
          _light: "{colors.teal.700}",
          _dark: "{colors.teal.300}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.teal.100}",
          _dark: "{colors.teal.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.teal.200}",
          _dark: "{colors.teal.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.teal.300}",
          _dark: "{colors.teal.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.teal.600}",
          _dark: "{colors.teal.600}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.teal.500}",
          _dark: "{colors.teal.500}",
        },
      },
      border: {
        value: {
          _light: "{colors.teal.500}",
          _dark: "{colors.teal.400}",
        },
      },
    },
    purple: {
      contrast: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.white}",
        },
      },
      fg: {
        value: {
          _light: "{colors.purple.700}",
          _dark: "{colors.purple.300}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.purple.100}",
          _dark: "{colors.purple.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.purple.200}",
          _dark: "{colors.purple.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.purple.300}",
          _dark: "{colors.purple.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.purple.600}",
          _dark: "{colors.purple.600}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.purple.500}",
          _dark: "{colors.purple.500}",
        },
      },
      border: {
        value: {
          _light: "{colors.purple.500}",
          _dark: "{colors.purple.400}",
        },
      },
    },
    pink: {
      contrast: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.white}",
        },
      },
      fg: {
        value: {
          _light: "{colors.pink.700}",
          _dark: "{colors.pink.300}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.pink.100}",
          _dark: "{colors.pink.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.pink.200}",
          _dark: "{colors.pink.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.pink.300}",
          _dark: "{colors.pink.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.pink.600}",
          _dark: "{colors.pink.600}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.pink.500}",
          _dark: "{colors.pink.500}",
        },
      },
      border: {
        value: {
          _light: "{colors.pink.500}",
          _dark: "{colors.pink.400}",
        },
      },
    },
    cyan: {
      contrast: {
        value: {
          _light: "{colors.white}",
          _dark: "{colors.white}",
        },
      },
      fg: {
        value: {
          _light: "{colors.cyan.700}",
          _dark: "{colors.cyan.300}",
        },
      },
      subtle: {
        value: {
          _light: "{colors.cyan.100}",
          _dark: "{colors.cyan.900}",
        },
      },
      muted: {
        value: {
          _light: "{colors.cyan.200}",
          _dark: "{colors.cyan.800}",
        },
      },
      emphasized: {
        value: {
          _light: "{colors.cyan.300}",
          _dark: "{colors.cyan.700}",
        },
      },
      solid: {
        value: {
          _light: "{colors.cyan.600}",
          _dark: "{colors.cyan.600}",
        },
      },
      focusRing: {
        value: {
          _light: "{colors.cyan.500}",
          _dark: "{colors.cyan.500}",
        },
      },
      border: {
        value: {
          _light: "{colors.cyan.500}",
          _dark: "{colors.cyan.400}",
        },
      },
    },
  },
  sizes: {
    mapMarkerWidth: {
      value: "26.2px",
    },
    mapMarkerHeight: {
      value: "41px",
    },
    mainContentMinHeight: {
      value: "0px",
    },
    mobileCardWidth: {
      value: "86vw",
    },
    mobileCardAccordionWidth: {
      value: "98%",
    },
  },
  radii: {
    l1: {
      value: "{radii.xs}",
    },
    l2: {
      value: "{radii.sm}",
    },
    l3: {
      value: "{radii.md}",
    },
  },
  shadows: {
    xs: {
      value: {
        _light:
          "0px 1px 2px {colors.gray.900/10}, 0px 0px 1px {colors.gray.900/20}",
        _dark: "0px 1px 1px {black/64}, 0px 0px 1px inset {colors.gray.300/20}",
      },
    },
    sm: {
      value: {
        _light:
          "0px 2px 4px {colors.gray.900/10}, 0px 0px 1px {colors.gray.900/30}",
        _dark: "0px 2px 4px {black/64}, 0px 0px 1px inset {colors.gray.300/30}",
      },
    },
    md: {
      value: {
        _light:
          "0px 4px 8px {colors.gray.900/10}, 0px 0px 1px {colors.gray.900/30}",
        _dark: "0px 4px 8px {black/64}, 0px 0px 1px inset {colors.gray.300/30}",
      },
    },
    lg: {
      value: {
        _light:
          "0px 8px 16px {colors.gray.900/10}, 0px 0px 1px {colors.gray.900/30}",
        _dark:
          "0px 8px 16px {black/64}, 0px 0px 1px inset {colors.gray.300/30}",
      },
    },
    xl: {
      value: {
        _light:
          "0px 16px 24px {colors.gray.900/10}, 0px 0px 1px {colors.gray.900/30}",
        _dark:
          "0px 16px 24px {black/64}, 0px 0px 1px inset {colors.gray.300/30}",
      },
    },
    "2xl": {
      value: {
        _light:
          "0px 24px 40px {colors.gray.900/16}, 0px 0px 1px {colors.gray.900/30}",
        _dark:
          "0px 24px 40px {black/64}, 0px 0px 1px inset {colors.gray.300/30}",
      },
    },
    inner: {
      value: {
        _light: "inset 0 2px 4px 0 {black/5}",
        _dark: "inset 0 2px 4px 0 black",
      },
    },
    inset: {
      value: {
        _light: "inset 0 0 0 1px {black/5}",
        _dark: "inset 0 0 0 1px {colors.gray.300/5}",
      },
    },
    card: {
      value: "{spacing.0} {spacing.1} {spacing.1.5} {colors.lightGrey}",
    },
    mobileButton: {
      value: "{spacing.0} {spacing.0} {spacing.0.5} {colors.lightGrey}",
    },
    search: {
      value:
        "{spacing.0} {spacing.1} {spacing.1.5} {-spacing.0.25} {colors.blackAlpha.200}, {spacing.0} {spacing.0.5} {spacing.1} {-spacing.0.25} {colors.blackAlpha.50}",
    },
  },
  assets: {
    mapMarkerUrl: {
      type: "url",
      value: 'url("/marker.svg")',
    },
  },
});
