name: CI/CD Pipeline

on: 
    push:
        branches:
            - add_ci_and_linting
    pull_request: 
        types: [opened, reopened]         
        branches:
            - master

jobs:
  lint_and_type_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install black mypy

      - name: Check code formatting with black
        run: black --check .

      - name: Type check with mypy
        run: mypy --config-file mypy.ini .

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        




