name: CI/CD Pipeline

on: 
    push:
        branches:
            - add_ci_and_linting
    pull_request: 
        types: [opened, reopened]         
        branches:
            - master

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install black
      - name: Run Black
        run: |
          black --check .




