name: Keep Serverless Functions Warm

on:
  schedule:
    - cron: '*/4 * * * *' # Every 4 minutes 24/7/365

  workflow_dispatch: 

jobs:
  ping-endpoints:
    runs-on: ubuntu-latest

    steps:
      - name: Ping health api
        run: curl -s -o /dev/null "https://www.safehome.report/api/health"